import type { CatalogEntry } from "./types";

/** Levantado em 09/09/2026 percorrendo as abas de src/components/atendimento/.
 *
 *  FORA DO CATÁLOGO — aba Cobertura (`atendimento_cob_chats`, `_cliente`,
 *  `_ticket`, `_tenants`): `useAtendimentoCobertura` roda com
 *  `enabled: isSuperAdmin` e NÃO filtra tenant — é visão cruzada entre
 *  empresas. Num painel de admin/head esses números seriam de todos os
 *  clientes do DoctorSaaS. Decisão pendente do owner.
 *
 *  Filtros reais da área, conferidos nos hooks: período, setor, agente, tipo
 *  (individual/grupo), plantão, segmento, área de atuação, estado, cidade,
 *  fornecedor e produto. São mais que os seis previstos na spec — Backlog e
 *  Clientes usam os quatro últimos.
 */
export const atendimento: CatalogEntry[] = [
  // ---------- Volume ----------
  {
    id: "at.volume_total",
    area: "atendimento",
    kind: "card",
    label: "Total de atendimentos",
    helpKey: "atendimento_volume_total",
    format: "integer",
    source: { provider: "atendimento.volume", path: "total" },
  },
  /** Na tela é UM card, "Novos vs Recorrentes", com os dois números juntos.
   *  Separado aqui porque num painel de 15 vagas o gestor escolhe um só. */
  {
    id: "at.volume_novos",
    area: "atendimento",
    kind: "card",
    label: "Clientes novos",
    helpKey: "atendimento_novos_recorrentes",
    format: "integer",
    source: { provider: "atendimento.volume", path: "novos" },
  },
  {
    id: "at.volume_recorrentes",
    area: "atendimento",
    kind: "card",
    label: "Clientes recorrentes",
    helpKey: "atendimento_novos_recorrentes",
    format: "integer",
    source: { provider: "atendimento.volume", path: "recorrentes" },
  },
  /** Mesmo caso: na tela é o card "Proativo vs Reativo". */
  {
    id: "at.volume_proativo",
    area: "atendimento",
    kind: "card",
    label: "Atendimentos proativos",
    helpKey: "atendimento_proativo_reativo",
    format: "integer",
    source: { provider: "atendimento.volume", path: "proativo" },
  },
  {
    id: "at.volume_reativo",
    area: "atendimento",
    kind: "card",
    label: "Atendimentos reativos",
    helpKey: "atendimento_proativo_reativo",
    format: "integer",
    source: { provider: "atendimento.volume", path: "reativo" },
  },
  {
    id: "at.volume_canais",
    area: "atendimento",
    kind: "chart",
    label: "Atendimentos por canal",
    format: "integer",
    source: { provider: "atendimento.volume", path: "canais" },
    pending: true,
  },
  {
    id: "at.volume_heatmap",
    area: "atendimento",
    kind: "chart",
    label: "Mapa de calor semanal",
    format: "integer",
    source: { provider: "atendimento.volume", path: "heatmap" },
    pending: true,
  },
  {
    id: "at.volume_top_motivos",
    area: "atendimento",
    kind: "chart",
    label: "Principais motivos de contato",
    helpKey: "atendimento_top_motivos",
    format: "integer",
    source: { provider: "atendimento.volume", path: "top_motivos" },
    pending: true,
  },

  // ---------- Velocidade ----------
  {
    id: "at.tme",
    area: "atendimento",
    kind: "card",
    label: "TME",
    helpKey: "atendimento_tme",
    format: "duration",
    source: { provider: "atendimento.velocidade", path: "tme_p50" },
  },
  {
    id: "at.frt",
    area: "atendimento",
    kind: "card",
    label: "1ª Resposta",
    helpKey: "atendimento_frt",
    format: "duration",
    source: { provider: "atendimento.velocidade", path: "frt_p50" },
  },
  {
    id: "at.tma",
    area: "atendimento",
    kind: "card",
    label: "TMA",
    helpKey: "atendimento_tma",
    format: "duration",
    source: { provider: "atendimento.velocidade", path: "tma_p50" },
  },
  {
    id: "at.tmr",
    area: "atendimento",
    kind: "card",
    label: "TMR",
    helpKey: "atendimento_tmr",
    format: "duration",
    source: { provider: "atendimento.velocidade", path: "tmr_p50" },
  },
  {
    id: "at.sla_frt_pct",
    area: "atendimento",
    kind: "card",
    label: "% dentro do SLA",
    helpKey: "atendimento_sla_frt",
    format: "percent",
    source: { provider: "atendimento.velocidade", path: "sla_pct" },
  },
  {
    id: "at.sla_util_pct",
    area: "atendimento",
    kind: "card",
    label: "% SLA (horário útil)",
    helpKey: "atendimento_sla_util",
    format: "percent",
    source: { provider: "atendimento.velocidade", path: "sla_util_pct" },
  },
  {
    id: "at.nao_atendido_pct",
    area: "atendimento",
    kind: "card",
    label: "Não Atendido",
    helpKey: "atendimento_nao_atendido",
    format: "percent",
    source: { provider: "atendimento.velocidade", path: "nao_atendido_pct" },
  },
  {
    id: "at.sla_por_setor",
    area: "atendimento",
    kind: "chart",
    label: "SLA por setor",
    helpKey: "atendimento_sla_frt",
    format: "percent",
    source: { provider: "atendimento.velocidade", path: "por_departamento" },
    pending: true,
  },
  /** Componente próprio, com hook próprio: não lê campo de bloco nenhum. */
  {
    id: "at.velocidade_timeline",
    area: "atendimento",
    kind: "chart",
    label: "Velocidade ao longo do tempo",
    format: "duration",
    source: { provider: "atendimento.velocidade_timeline", path: "self" },
    span: 4,
    render: "VelocidadeTimeline",
  },
  {
    id: "at.latencia_histograma",
    area: "atendimento",
    kind: "chart",
    label: "Distribuição de latência",
    format: "integer",
    source: { provider: "atendimento.latencia", path: "self" },
    span: 2,
    render: "LatenciaHistograma",
  },

  // ---------- Tempo real ----------
  {
    id: "at.fila",
    area: "atendimento",
    kind: "card",
    label: "Fila Agora",
    helpKey: "atendimento_fila",
    format: "integer",
    source: { provider: "atendimento.tempo_real", path: "fila" },
  },
  {
    id: "at.espera_mais_antiga",
    area: "atendimento",
    kind: "card",
    label: "Espera Mais Antiga",
    helpKey: "atendimento_espera_mais_antigo",
    format: "duration",
    source: { provider: "atendimento.tempo_real", path: "espera_mais_antigo_seg" },
  },
  {
    id: "at.em_atendimento",
    area: "atendimento",
    kind: "card",
    label: "Em Atendimento",
    helpKey: "atendimento_em_atendimento",
    format: "integer",
    source: { provider: "atendimento.tempo_real", path: "em_atendimento" },
  },
  {
    id: "at.agentes_online",
    area: "atendimento",
    kind: "card",
    label: "Agentes Online",
    helpKey: "atendimento_agentes_online",
    format: "integer",
    source: { provider: "atendimento.tempo_real", path: "agentes_online" },
  },
  {
    id: "at.sla_estourando",
    area: "atendimento",
    kind: "card",
    label: "Estourando SLA",
    helpKey: "atendimento_sla_estourando",
    format: "integer",
    source: { provider: "atendimento.tempo_real", path: "sla_estourando" },
  },
  {
    id: "at.parados_24h",
    area: "atendimento",
    kind: "card",
    label: "Parados > 24h",
    helpKey: "atendimento_parados_24h",
    format: "integer",
    source: { provider: "atendimento.tempo_real", path: "parados_24h" },
  },

  // ---------- Backlog ----------
  {
    id: "at.backlog_abertos",
    area: "atendimento",
    kind: "card",
    label: "Backlog aberto",
    helpKey: "atendimento_backlog_abertos",
    format: "integer",
    source: { provider: "atendimento.backlog", path: "abertos" },
  },
  {
    id: "at.backlog_orfaos",
    area: "atendimento",
    kind: "card",
    label: "Órfãos",
    helpKey: "atendimento_backlog_orfaos",
    format: "integer",
    source: { provider: "atendimento.backlog", path: "orfaos" },
  },
  {
    id: "at.backlog_parados",
    area: "atendimento",
    kind: "card",
    label: "Parados (>7d)",
    helpKey: "atendimento_backlog_parados",
    format: "integer",
    source: { provider: "atendimento.backlog", path: "parados" },
  },
  {
    id: "at.backlog_vencidos",
    area: "atendimento",
    kind: "card",
    label: "Vencidos",
    helpKey: "atendimento_backlog_vencidos",
    format: "integer",
    source: { provider: "atendimento.backlog", path: "vencidos" },
  },
  {
    id: "at.backlog_aging",
    area: "atendimento",
    kind: "chart",
    label: "Envelhecimento do backlog",
    format: "integer",
    source: { provider: "atendimento.backlog", path: "aging" },
    pending: true,
  },
  {
    id: "at.backlog_por_prioridade",
    area: "atendimento",
    kind: "chart",
    label: "Backlog por prioridade",
    format: "integer",
    source: { provider: "atendimento.backlog", path: "por_prioridade" },
    pending: true,
  },

  // ---------- Agentes ----------
  {
    id: "at.encerrados_periodo",
    area: "atendimento",
    kind: "card",
    label: "Encerrados no Período",
    helpKey: "atendimento_encerrados_periodo",
    format: "integer",
    source: { provider: "atendimento.agentes", path: "total_encerrados" },
  },
  {
    id: "at.agentes_ativos",
    area: "atendimento",
    kind: "card",
    label: "Agentes Ativos",
    helpKey: "atendimento_agentes_ativos",
    format: "integer",
    source: { provider: "atendimento.agentes", path: "agentes_ativos" },
  },
  {
    id: "at.csat_equipe",
    area: "atendimento",
    kind: "card",
    label: "CSAT da Equipe",
    helpKey: "atendimento_csat_equipe",
    format: "decimal",
    source: { provider: "atendimento.agentes", path: "csat_equipe" },
  },
  {
    id: "at.reabertura",
    area: "atendimento",
    kind: "card",
    label: "Taxa de Reabertura",
    helpKey: "atendimento_reabertura",
    format: "percent",
    source: { provider: "atendimento.agentes", path: "reabertura_equipe_pct" },
  },
  {
    id: "at.ranking_agentes",
    area: "atendimento",
    kind: "chart",
    label: "Ranking de agentes",
    format: "integer",
    source: { provider: "atendimento.agentes", path: "agentes" },
    pending: true,
  },

  // ---------- Satisfação ----------
  {
    id: "at.csat_media",
    area: "atendimento",
    kind: "card",
    label: "CSAT Médio",
    helpKey: "atendimento_csat_media",
    format: "decimal",
    source: { provider: "atendimento.satisfacao", path: "media" },
  },
  {
    id: "at.csat_response_rate",
    area: "atendimento",
    kind: "card",
    label: "Taxa de Resposta",
    helpKey: "atendimento_response_rate",
    format: "percent",
    source: { provider: "atendimento.satisfacao", path: "response_rate_pct" },
  },
  /** O percentual é calculado dentro da SatisfacaoTab a partir de
   *  `div_neg_nota_alta` e `div_neg_total`. A F3 decide se o cálculo sobe
   *  para o provider ou se o card recebe os dois campos. */
  {
    id: "at.csat_divergencia",
    area: "atendimento",
    kind: "card",
    label: "Divergência CSAT × Sentimento",
    helpKey: "atendimento_divergencia",
    format: "percent",
    source: { provider: "atendimento.satisfacao", path: "div_neg_nota_alta" },
  },
  {
    id: "at.atendeu_na_hora",
    area: "atendimento",
    kind: "card",
    label: "Atendeu na Hora",
    helpKey: "atendimento_atendeu_na_hora",
    format: "percent",
    source: { provider: "atendimento.satisfacao", path: "atendeu_na_hora_pct" },
  },
  {
    id: "at.csat_distribuicao",
    area: "atendimento",
    kind: "chart",
    label: "Distribuição das notas",
    helpKey: "atendimento_csat_media",
    format: "integer",
    source: { provider: "atendimento.satisfacao", path: "distribuicao" },
    pending: true,
  },

  // ---------- URA ----------
  {
    id: "at.ura_enviadas",
    area: "atendimento",
    kind: "card",
    label: "URAs Enviadas",
    helpKey: "atendimento_ura_enviadas",
    format: "integer",
    source: { provider: "atendimento.ura", path: "enviadas" },
  },
  {
    id: "at.ura_completadas_pct",
    area: "atendimento",
    kind: "card",
    label: "URA Concluída",
    helpKey: "atendimento_ura_completadas",
    format: "percent",
    source: { provider: "atendimento.ura", path: "completadas_pct" },
  },
  {
    id: "at.ura_timeout_pct",
    area: "atendimento",
    kind: "card",
    label: "Timeout / Fallback",
    helpKey: "atendimento_ura_timeout",
    format: "percent",
    source: { provider: "atendimento.ura", path: "timeout_pct" },
  },
  {
    id: "at.ura_confusa_pct",
    area: "atendimento",
    kind: "card",
    label: "URA Confusa",
    helpKey: "atendimento_ura_confusa",
    format: "percent",
    source: { provider: "atendimento.ura", path: "confusas_pct" },
  },

  // ---------- Taxonomia ----------
  {
    id: "at.tax_total",
    area: "atendimento",
    kind: "card",
    label: "Total de Tickets",
    helpKey: "atendimento_tax_total",
    format: "integer",
    source: { provider: "atendimento.taxonomia", path: "total" },
  },
  /** A tela mostra `por_produto.length`: a contagem é feita no componente. */
  {
    id: "at.tax_produtos",
    area: "atendimento",
    kind: "card",
    label: "Produtos com Tickets",
    helpKey: "atendimento_tax_produto",
    format: "integer",
    source: { provider: "atendimento.taxonomia", path: "por_produto" },
  },
  {
    id: "at.tax_categorias",
    area: "atendimento",
    kind: "card",
    label: "Categorias Ativas",
    helpKey: "atendimento_tax_categoria",
    format: "integer",
    source: { provider: "atendimento.taxonomia", path: "por_categoria" },
  },
  {
    id: "at.tax_por_categoria",
    area: "atendimento",
    kind: "chart",
    label: "Tickets por categoria",
    helpKey: "atendimento_tax_categoria",
    format: "integer",
    source: { provider: "atendimento.taxonomia", path: "por_categoria" },
    pending: true,
  },
  {
    id: "at.tax_heatmap",
    area: "atendimento",
    kind: "chart",
    label: "Mapa de calor de tickets",
    format: "integer",
    source: { provider: "atendimento.taxonomia", path: "heatmap" },
    pending: true,
  },
  {
    id: "at.tax_ofensores",
    area: "atendimento",
    kind: "chart",
    label: "Maiores ofensores",
    format: "integer",
    source: { provider: "atendimento.taxonomia", path: "ofensores" },
    pending: true,
  },

  // ---------- Clientes ----------
  {
    id: "at.cli_clientes",
    area: "atendimento",
    kind: "card",
    label: "Clientes atendidos",
    helpKey: "atendimento_cli_clientes",
    format: "integer",
    source: { provider: "atendimento.clientes", path: "totais.clientes" },
  },
  {
    id: "at.cli_mrr",
    area: "atendimento",
    kind: "card",
    label: "MRR coberto",
    helpKey: "atendimento_cli_mrr",
    format: "currency",
    source: { provider: "atendimento.clientes", path: "totais.mrr_coberto" },
  },
  {
    id: "at.cli_risco",
    area: "atendimento",
    kind: "card",
    label: "Risco alto",
    helpKey: "atendimento_cli_risco",
    format: "integer",
    source: { provider: "atendimento.clientes", path: "totais.risco_alto" },
  },
  /** Mostra o NOME do cliente, não um número: a ClientesTab lê o primeiro
   *  item de `clientes` e resolve o nome. Daí o format "text". */
  {
    id: "at.cli_ofensor",
    area: "atendimento",
    kind: "card",
    label: "Ofensor #1",
    helpKey: "atendimento_cli_ofensor",
    format: "text",
    source: { provider: "atendimento.clientes", path: "clientes" },
  },
];
