import type { CatalogEntry } from "./types";

/** Levantado em 09/09/2026 percorrendo src/components/dashboard/tabs/.
 *
 *  Um provider por hook, como em Atendimento:
 *    financeiro.dashboard      → useDashboardData (KPIMetrics, ~50 campos)
 *    financeiro.visao_geral    → useVisaoGeralExtras
 *    financeiro.crescimento    → useCrescimentoExtras
 *    financeiro.cancelamentos  → useCancelamentosExtras
 *    financeiro.cohort         → useCohortLogos / useCohortRevenue / useCohortForecast
 *
 *  FORA DO CATÁLOGO — aba Distribuição. `useDistribuicaoExtras` e
 *  `useVendasExtras` não servem indicador: são hooks de exploração que
 *  recebem a dimensão como parâmetro (`useVendasExplorer(filters, dim)`,
 *  `useCarteiraBreakdown(filters, dim, uf)`). A aba é um mapa interativo com
 *  seletor de dimensão, não um conjunto de números fixos. Não há o que
 *  replicar num painel diário.
 *
 *  FORA DO CATÁLOGO — "Margem nova (R$)" e "Margem % nova" da aba Vendas.
 *  Os dois saem de `useVendasExplorer(filters, expDim)` somando o breakdown,
 *  e `expDim` é o seletor de dimensão da tela: o número depende de estado de
 *  UI, não existe fora dela. Entrariam no painel só com uma dimensão fixa —
 *  decisão pendente do owner.
 *
 *  DOIS VERBETES PARA O MESMO NÚMERO: "Novos Clientes" aparece no Crescimento
 *  com `novos_clientes_mes` e em Vendas com `novos_clientes_vendas`, lendo o
 *  mesmo `novosClientes`. O catálogo usa o de Vendas e deixa o outro na lista
 *  de verbetes órfãos, para o owner decidir qual sobrevive.
 *
 *  TODO GRÁFICO DAQUI ESTÁ `pending`. A regra que apliquei: um gráfico só sai
 *  de pending quando está confirmado que o componente aceita os dados por
 *  propriedade. Nenhum dos componentes de `charts/` foi conferido ainda —
 *  isso é trabalho da F3. Pela §5.0 da spec, conferir NÃO autoriza alterá-los.
 */
export const financeiro: CatalogEntry[] = [
  // ---------- Visão Geral ----------
  {
    id: "fin.mrr",
    area: "financeiro",
    kind: "card",
    label: "MRR Atual",
    helpKey: "mrr_snapshot",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "mrr" },
  },
  {
    id: "fin.clientes_ativos",
    area: "financeiro",
    kind: "card",
    label: "Clientes Ativos",
    helpKey: "clientes_ativos",
    format: "integer",
    source: { provider: "financeiro.dashboard", path: "clientesAtivos" },
  },
  {
    id: "fin.ticket_medio",
    area: "financeiro",
    kind: "card",
    label: "Ticket Médio",
    helpKey: "ticket_medio",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "ticketMedio" },
  },
  {
    id: "fin.arr",
    area: "financeiro",
    kind: "card",
    label: "ARR",
    helpKey: "arr",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "arr" },
  },
  {
    id: "fin.faturamento_total",
    area: "financeiro",
    kind: "card",
    label: "Faturamento total",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "faturamentoTotal" },
  },
  {
    id: "fin.rule_of_40",
    area: "financeiro",
    kind: "card",
    label: "Rule of 40",
    helpKey: "rule_of_40",
    format: "decimal",
    source: { provider: "financeiro.crescimento", path: "ruleOf40" },
  },
  {
    id: "fin.cac_payback",
    area: "financeiro",
    kind: "card",
    label: "CAC Payback",
    helpKey: "cac_payback",
    format: "decimal",
    source: { provider: "financeiro.dashboard", path: "cacPayback" },
  },
  {
    id: "fin.ltv_cac",
    area: "financeiro",
    kind: "card",
    label: "LTV / CAC",
    helpKey: "ltv_cac_recorrente",
    format: "ratio",
    source: { provider: "financeiro.dashboard", path: "ltvCac" },
  },
  {
    id: "fin.tenure_medio",
    area: "financeiro",
    kind: "card",
    label: "Tenure Médio",
    helpKey: "tenure_medio",
    format: "decimal",
    source: { provider: "financeiro.visao_geral", path: "tenureMedio" },
  },
  {
    id: "fin.nrr",
    area: "financeiro",
    kind: "card",
    label: "NRR",
    helpKey: "nrr",
    format: "percent",
    source: { provider: "financeiro.dashboard", path: "nrr" },
  },
  {
    id: "fin.grr",
    area: "financeiro",
    kind: "card",
    label: "GRR",
    helpKey: "grr",
    format: "percent",
    source: { provider: "financeiro.dashboard", path: "grr" },
  },
  {
    id: "fin.concentracao_top10",
    area: "financeiro",
    kind: "card",
    label: "Concentração Top 10",
    helpKey: "concentracao_top10",
    format: "percent",
    source: { provider: "financeiro.dashboard", path: "concentracaoTop10" },
  },
  {
    id: "fin.quick_ratio",
    area: "financeiro",
    kind: "card",
    label: "Quick Ratio",
    helpKey: "quick_ratio",
    format: "ratio",
    source: { provider: "financeiro.dashboard", path: "quickRatio" },
  },
  {
    id: "fin.ltv_meses",
    area: "financeiro",
    kind: "card",
    label: "LTV (meses)",
    format: "decimal",
    source: { provider: "financeiro.dashboard", path: "ltvMeses" },
  },
  {
    id: "fin.ltv_reais",
    area: "financeiro",
    kind: "card",
    label: "LTV (R$)",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "ltvReais" },
  },
  {
    id: "fin.cac",
    area: "financeiro",
    kind: "card",
    label: "CAC",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "cac" },
  },
  {
    id: "fin.margem_contribuicao",
    area: "financeiro",
    kind: "card",
    label: "Margem de contribuição",
    format: "percent",
    source: { provider: "financeiro.dashboard", path: "margemContribuicao" },
  },
  {
    id: "fin.receita_por_funcionario",
    area: "financeiro",
    kind: "card",
    label: "Receita por funcionário",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "revenuePerFuncionario" },
  },
  {
    id: "fin.mrr_serie",
    area: "financeiro",
    kind: "chart",
    label: "Evolução do MRR · 12 meses",
    helpKey: "mrr_snapshot",
    format: "currency",
    source: { provider: "financeiro.visao_geral", path: "mrrSeries" },
    span: 4,
    chart: { tipo: "linha", fonte: "lista", rotulo: "dataCorte", valor: "mrr" },
  },

  // ---------- Crescimento ----------
  {
    id: "fin.net_new_mrr",
    area: "financeiro",
    kind: "card",
    label: "Net New MRR",
    helpKey: "net_new_mrr",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "netNewMrr" },
  },
  {
    id: "fin.growth_rate_mom",
    area: "financeiro",
    kind: "card",
    label: "Growth Rate MoM",
    helpKey: "mrr_growth_rate_mom",
    format: "percent",
    source: { provider: "financeiro.crescimento", path: "growthRateMoM" },
  },
  {
    id: "fin.growth_rate_qoq",
    area: "financeiro",
    kind: "card",
    label: "Growth Rate QoQ",
    format: "percent",
    source: { provider: "financeiro.crescimento", path: "growthRateQoQ" },
  },
  {
    id: "fin.growth_rate_yoy",
    area: "financeiro",
    kind: "card",
    label: "Growth Rate YoY",
    format: "percent",
    source: { provider: "financeiro.crescimento", path: "growthRateYoY" },
  },
  {
    id: "fin.arr_growth_yoy",
    area: "financeiro",
    kind: "card",
    label: "ARR Growth YoY",
    helpKey: "arr_growth_yoy",
    format: "percent",
    source: { provider: "financeiro.crescimento", path: "arrGrowthYoY" },
  },
  {
    id: "fin.growth_persistence",
    area: "financeiro",
    kind: "card",
    label: "Growth Persistence",
    helpKey: "growth_persistence",
    format: "decimal",
    source: { provider: "financeiro.crescimento", path: "growthPersistence" },
  },
  {
    id: "fin.expansion_rate",
    area: "financeiro",
    kind: "card",
    label: "Expansion Rate",
    helpKey: "expansion_rate",
    format: "percent",
    source: { provider: "financeiro.crescimento", path: "expansionRate" },
  },
  {
    id: "fin.net_logo_growth",
    area: "financeiro",
    kind: "card",
    label: "Net Logo Growth",
    helpKey: "net_logo_growth",
    format: "integer",
    source: { provider: "financeiro.crescimento", path: "netLogoGrowth" },
  },
  {
    id: "fin.logo_growth_rate",
    area: "financeiro",
    kind: "card",
    label: "Logo Growth Rate",
    helpKey: "logo_growth_rate",
    format: "percent",
    source: { provider: "financeiro.crescimento", path: "logoGrowthRate" },
  },
  {
    id: "fin.arpa_novo",
    area: "financeiro",
    kind: "card",
    label: "ARPA — clientes novos",
    format: "currency",
    source: { provider: "financeiro.crescimento", path: "arpaNovo" },
  },
  {
    id: "fin.arpa_base",
    area: "financeiro",
    kind: "card",
    label: "ARPA — base atual",
    format: "currency",
    source: { provider: "financeiro.crescimento", path: "arpaBase" },
  },
  {
    id: "fin.cac_por_logo",
    area: "financeiro",
    kind: "card",
    label: "CAC por Logo",
    helpKey: "cac_por_logo",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "cac" },
  },
  {
    id: "fin.burn_multiple",
    area: "financeiro",
    kind: "card",
    label: "Burn Multiple",
    helpKey: "burn_multiple",
    format: "ratio",
    source: { provider: "financeiro.crescimento", path: "burnMultiple" },
  },
  {
    id: "fin.magic_number",
    area: "financeiro",
    kind: "card",
    label: "Magic Number",
    helpKey: "magic_number",
    format: "ratio",
    source: { provider: "financeiro.crescimento", path: "magicNumber" },
  },
  {
    id: "fin.reativacoes_qtd",
    area: "financeiro",
    kind: "card",
    label: "Reativações",
    format: "integer",
    source: { provider: "financeiro.crescimento", path: "reativacoesQtd" },
  },
  {
    id: "fin.reativacoes_mrr",
    area: "financeiro",
    kind: "card",
    label: "MRR reativado",
    format: "currency",
    source: { provider: "financeiro.crescimento", path: "reativacoesMrr" },
  },
  {
    id: "fin.net_new_media_3m",
    area: "financeiro",
    kind: "card",
    label: "Net New — média 3 meses",
    format: "currency",
    source: { provider: "financeiro.crescimento", path: "netNewHistorico.media3m" },
  },
  {
    id: "fin.net_new_media_12m",
    area: "financeiro",
    kind: "card",
    label: "Net New — média 12 meses",
    format: "currency",
    source: { provider: "financeiro.crescimento", path: "netNewHistorico.media12m" },
  },

  // ---------- Composição do Net New (breakdown) ----------
  {
    id: "fin.upsell_mrr",
    area: "financeiro",
    kind: "card",
    label: "Upsell",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "upsellMrr" },
  },
  {
    id: "fin.cross_sell_mrr",
    area: "financeiro",
    kind: "card",
    label: "Cross-sell",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "crossSellMrr" },
  },
  {
    id: "fin.downsell_mrr",
    area: "financeiro",
    kind: "card",
    label: "Downsell",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "downsellMrr" },
  },
  {
    id: "fin.reajuste_mrr",
    area: "financeiro",
    kind: "card",
    label: "Reajuste",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "reajusteMrr" },
  },
  {
    id: "fin.net_new_stacked",
    area: "financeiro",
    kind: "chart",
    label: "Composição do Net New MRR",
    helpKey: "net_new_mrr",
    format: "currency",
    source: { provider: "financeiro.crescimento", path: "netNewHistorico" },
    pending: true,
  },
  {
    id: "fin.mrr_forecast",
    area: "financeiro",
    kind: "chart",
    label: "MRR com projeção de 90 dias",
    format: "currency",
    source: { provider: "financeiro.crescimento", path: "mrrForecast" },
    pending: true,
  },

  // ---------- Vendas ----------
  {
    id: "fin.novos_clientes",
    area: "financeiro",
    kind: "card",
    label: "Novos Clientes",
    helpKey: "novos_clientes_vendas",
    format: "integer",
    source: { provider: "financeiro.dashboard", path: "novosClientes" },
  },
  {
    id: "fin.new_mrr",
    area: "financeiro",
    kind: "card",
    label: "New MRR",
    helpKey: "new_mrr_vendas",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "newMrr" },
  },
  {
    id: "fin.receita_ativacao",
    area: "financeiro",
    kind: "card",
    label: "Receita de Ativação",
    helpKey: "receita_ativacao",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "receitaAtivacao" },
  },
  {
    id: "fin.total_implantacao",
    area: "financeiro",
    kind: "card",
    label: "Total de implantação",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "totalImplantacao" },
  },
  /** A VendasTab calcula na hora: newMrr ÷ novosClientes. Pela §5.0 o painel
   *  refaz a conta do seu lado, a partir do campo cru. */
  {
    id: "fin.ticket_medio_novos",
    area: "financeiro",
    kind: "card",
    label: "Ticket Médio (Novos)",
    helpKey: "ticket_medio_novos",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "newMrr" },
  },
  /** A VendasTab soma newMrr + upsell + cross. O painel refaz a conta (§5.0);
   *  o path aponta a primeira parcela. */
  {
    id: "fin.mrr_adicionado",
    area: "financeiro",
    kind: "card",
    label: "MRR Adicionado",
    helpKey: "mrr_adicionado",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "newMrr" },
  },
  {
    id: "fin.setup_medio",
    area: "financeiro",
    kind: "card",
    label: "Setup Médio",
    helpKey: "setup_medio",
    format: "currency",
    source: { provider: "financeiro.dashboard", path: "totalImplantacao" },
  },

  // ---------- Cancelamentos ----------
  {
    id: "fin.cancelamentos_qtd",
    area: "financeiro",
    kind: "card",
    label: "Cancelamentos (Qtde)",
    helpKey: "cancelamentos_qtd",
    format: "integer",
    source: { provider: "financeiro.cancelamentos", path: "cancelamentosQtd" },
  },
  {
    id: "fin.mrr_cancelado",
    area: "financeiro",
    kind: "card",
    label: "MRR Perdido (bruto)",
    helpKey: "mrr_cancelado",
    format: "currency",
    source: { provider: "financeiro.cancelamentos", path: "mrrCancelado" },
  },
  {
    id: "fin.mrr_liquido_perdido",
    area: "financeiro",
    kind: "card",
    label: "MRR perdido (líquido)",
    format: "currency",
    source: { provider: "financeiro.cancelamentos", path: "mrrLiquidoPerdido" },
  },
  {
    id: "fin.churn_rate_carteira",
    area: "financeiro",
    kind: "card",
    label: "Churn Rate (Carteira)",
    helpKey: "churn_rate_carteira",
    format: "percent",
    source: { provider: "financeiro.cancelamentos", path: "churnRateLogo" },
  },
  {
    id: "fin.churn_rate_receita",
    area: "financeiro",
    kind: "card",
    label: "Churn Rate (Receita)",
    helpKey: "churn_rate_receita",
    format: "percent",
    source: { provider: "financeiro.cancelamentos", path: "churnRateMrr" },
  },
  {
    id: "fin.early_churn_qtd",
    area: "financeiro",
    kind: "card",
    label: "Early churn (qtde)",
    format: "integer",
    source: { provider: "financeiro.cancelamentos", path: "earlyChurnQtd" },
  },
  {
    id: "fin.early_churn_rate",
    area: "financeiro",
    kind: "card",
    label: "Early churn (taxa)",
    format: "percent",
    source: { provider: "financeiro.cancelamentos", path: "earlyChurnRate" },
  },
  {
    id: "fin.winback_rate",
    area: "financeiro",
    kind: "card",
    label: "Winback 12 meses",
    format: "percent",
    source: { provider: "financeiro.cancelamentos", path: "winbackRate12m" },
  },
  {
    id: "fin.tenure_medio_cancelados",
    area: "financeiro",
    kind: "card",
    label: "Tempo de casa ao cancelar",
    format: "decimal",
    source: { provider: "financeiro.cancelamentos", path: "tenureMedioCancDias" },
  },
  {
    id: "fin.cac_perdido",
    area: "financeiro",
    kind: "card",
    label: "CAC perdido",
    format: "currency",
    source: { provider: "financeiro.cancelamentos", path: "cacPerdido" },
  },
  {
    id: "fin.churn_por_categoria",
    area: "financeiro",
    kind: "chart",
    label: "Churn por categoria",
    format: "currency",
    source: { provider: "financeiro.cancelamentos", path: "categorias" },
    pending: true,
  },
  {
    id: "fin.churn_por_tempo_casa",
    area: "financeiro",
    kind: "chart",
    label: "Churn por tempo de casa",
    format: "integer",
    source: { provider: "financeiro.cancelamentos", path: "buckets" },
    pending: true,
  },
  {
    id: "fin.churn_top_motivos",
    area: "financeiro",
    kind: "chart",
    label: "Principais motivos de cancelamento",
    format: "integer",
    source: { provider: "financeiro.cancelamentos", path: "topMotivos" },
    span: 3,
    chart: { tipo: "barras", fonte: "lista", rotulo: "motivo", valor: "qtd", limite: 8 },
  },
];
