
-- 1. Limpar tabela produtos
ALTER TABLE produtos DROP COLUMN IF EXISTS codigo_fornecedor;
ALTER TABLE produtos DROP COLUMN IF EXISTS link_portal;
ALTER TABLE produtos DROP COLUMN IF EXISTS fornecedor_id;

-- 2. Criar tabela origens_venda
CREATE TABLE public.origens_venda (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL
);
ALTER TABLE origens_venda ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_read_origens_venda" ON origens_venda FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write_origens_venda" ON origens_venda FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 3. Dropar view que depende de origem_venda
DROP VIEW IF EXISTS vw_clientes_financeiro;

-- 4. Trocar coluna origem_venda (text) por origem_venda_id (FK) em clientes
ALTER TABLE clientes DROP COLUMN IF EXISTS origem_venda;
ALTER TABLE clientes ADD COLUMN origem_venda_id bigint REFERENCES origens_venda(id);
CREATE INDEX idx_clientes_origem_venda ON clientes(origem_venda_id);

-- 5. Recriar view com origem_venda_id
CREATE OR REPLACE VIEW vw_clientes_financeiro AS
SELECT 
    id, razao_social, nome_fantasia, cnpj, email, telefone_contato, telefone_whatsapp,
    observacao_cliente, observacao_negociacao, origem_venda_id,
    data_cadastro, estado_id, cidade_id, area_atuacao_id, segmento_id, modelo_contrato_id,
    unidade_base_id, data_venda, funcionario_id, recorrencia, produto_id,
    valor_ativacao, forma_pagamento_ativacao_id, mensalidade, forma_pagamento_mensalidade_id,
    custo_operacao, imposto_percentual, custo_fixo_percentual,
    cancelado, data_cancelamento, motivo_cancelamento_id, observacao_cancelamento,
    created_at, updated_at, cert_a1_vencimento, cert_a1_ultima_venda_em, cert_a1_ultimo_vendedor_id,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round(mensalidade * COALESCE(imposto_percentual, 0), 2) ELSE 0::numeric END AS impostos_rs,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round(mensalidade * COALESCE(custo_fixo_percentual, 0), 2) ELSE 0::numeric END AS fixos_rs,
    COALESCE(custo_operacao, 0) AS valor_repasse,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round(mensalidade - COALESCE(custo_operacao, 0), 2) ELSE 0::numeric END AS lucro_bruto,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round(mensalidade - COALESCE(custo_operacao, 0) - round(mensalidade * COALESCE(imposto_percentual, 0), 2) - round(mensalidade * COALESCE(custo_fixo_percentual, 0), 2), 2) ELSE 0::numeric END AS lucro_real,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round((mensalidade - COALESCE(custo_operacao, 0)) / mensalidade * 100, 2) ELSE 0::numeric END AS margem_bruta_percent,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round((mensalidade - COALESCE(custo_operacao, 0) - round(mensalidade * COALESCE(imposto_percentual, 0), 2) - round(mensalidade * COALESCE(custo_fixo_percentual, 0), 2)) / mensalidade * 100, 2) ELSE 0::numeric END AS margem_contribuicao,
    CASE WHEN COALESCE(custo_operacao, 0) > 0 THEN round(mensalidade / custo_operacao, 2) ELSE NULL::numeric END AS fator_preco_cogs_x,
    CASE WHEN COALESCE(custo_operacao, 0) > 0 THEN round((mensalidade - custo_operacao) / custo_operacao * 100, 2) ELSE NULL::numeric END AS markup_cogs_percent
FROM clientes c;
