DROP VIEW IF EXISTS vw_clientes_financeiro;

CREATE VIEW vw_clientes_financeiro AS
SELECT id,
    codigo_sequencial,
    razao_social,
    nome_fantasia,
    cnpj,
    email,
    telefone_contato,
    telefone_whatsapp,
    observacao_cliente,
    observacao_negociacao,
    origem_venda_id,
    data_cadastro,
    estado_id,
    cidade_id,
    area_atuacao_id,
    segmento_id,
    modelo_contrato_id,
    unidade_base_id,
    data_venda,
    funcionario_id,
    recorrencia,
    produto_id,
    valor_ativacao,
    forma_pagamento_ativacao_id,
    mensalidade,
    forma_pagamento_mensalidade_id,
    custo_operacao,
    imposto_percentual,
    custo_fixo_percentual,
    cancelado,
    data_cancelamento,
    motivo_cancelamento_id,
    observacao_cancelamento,
    created_at,
    updated_at,
    cert_a1_vencimento,
    cert_a1_ultima_venda_em,
    cert_a1_ultimo_vendedor_id,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round(mensalidade * COALESCE(imposto_percentual, 0), 2) ELSE 0 END AS impostos_rs,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round(mensalidade * COALESCE(custo_fixo_percentual, 0), 2) ELSE 0 END AS fixos_rs,
    COALESCE(custo_operacao, 0) AS valor_repasse,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round(mensalidade - COALESCE(custo_operacao, 0), 2) ELSE 0 END AS lucro_bruto,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round(mensalidade - COALESCE(custo_operacao, 0) - round(mensalidade * COALESCE(imposto_percentual, 0), 2) - round(mensalidade * COALESCE(custo_fixo_percentual, 0), 2), 2) ELSE 0 END AS lucro_real,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round((mensalidade - COALESCE(custo_operacao, 0)) / mensalidade * 100, 2) ELSE 0 END AS margem_bruta_percent,
    CASE WHEN mensalidade IS NOT NULL AND mensalidade > 0 THEN round((mensalidade - COALESCE(custo_operacao, 0) - round(mensalidade * COALESCE(imposto_percentual, 0), 2) - round(mensalidade * COALESCE(custo_fixo_percentual, 0), 2)) / mensalidade * 100, 2) ELSE 0 END AS margem_contribuicao,
    CASE WHEN COALESCE(custo_operacao, 0) > 0 THEN round(mensalidade / custo_operacao, 2) ELSE NULL END AS fator_preco_cogs_x,
    CASE WHEN COALESCE(custo_operacao, 0) > 0 THEN round((mensalidade - custo_operacao) / custo_operacao * 100, 2) ELSE NULL END AS markup_cogs_percent
FROM clientes c;